config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  resources :purchases, except: :show
  resources :categories, except: :show
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/controllers/top_controller.rb
# frozen_string_literal: true

# TopController
# アプリのトップ画面に関連する Controller.
# サインイン不要.
class TopController < ApplicationController
  def index; end
end

app/views/top/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% if user_signed_in? %>
        <%# サインインしている場合の表示. %>
        <h2><%= t('.top_menu') %></h2>
        <ul>
          <li><%= link_to(Purchase.model_name.human, purchases_path) %></li>
          <ul>
            <li>普段の買い物などの収入や支出を記録して見ることができます。</li>
          </ul>
          <%= link_to(new_purchase_path) do %>
            <span class="btn btn-primary my-2"><%= t('.new_purchase', default: 'New Purchase') %></span>
          <% end %>
          <li><%= link_to(Category.model_name.human, categories_path) %></li>
          <ul>
            <li>カテゴリーを登録して、収入や支出を分類することができます。</li>
          </ul>
        </ul>
      <% else %>
        <%# サインインしていない場合の表示. %>
        <h2><%= t('.kakeibo') %></h2>
        <%# TODO: i18n 対応. %>
        <p>このアプリでは、日々の収入・支出を記録できます。</p>
        <p>記録した収入や支出は後で見ることができるので、金銭管理の手助けになります！</p>
        <p><%= link_to(t('.sign_in'), new_user_session_path, class: 'btn btn-lg btn-primary') %></p>
        <p><%= link_to(t('.sign_up'), new_user_registration_path, class: 'btn btn-lg btn-success') %></p>
      <% end %>
    </div>
  </div>
</div>